name: Deploy

on:
  create:
    tags:
      - '*'

jobs:

  # check_for_new_tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Verificar nova tag
  #       id: tag_check
  #       run: 'echo "Nova tag criada: ${{ github.ref }}"'

  deploy_to_netlify:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Netlify (Manual)
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
