name: Deploy Para Netlify

on:
  create:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa repositorio
        uses: actions/checkout@master
      
      - name: Configura node
        uses: actions/setup-node@master
        with:
          node-version: '10'

      - name: instala dependencias
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy para o Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          TRIGGER_MANUAL: ${{ github.event_name == 'workflow_dispatch' }}
        run: npx netlify deploy --prod

  # deploy_to_netlify:
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to Netlify (Manual)
  #       uses: netlify/actions/cli@master
  #       with:
  #         args: deploy --prod
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
